### ISSUE TITLE
List fields request exception

### ISSUE THREAD

**Issue by dakk** [beardon/mws-api#42]
When I try to use an API where the argument is a list, I got an exception:

```
mws.Products.GetMatchingProduct({ MarketplaceId: market, ASINList: [asin] }).then(function ({ result, metadata }) {
});
```

```
/home/dakk/Repositories/MyRepos/ProductsBroker/node_modules/mws-api/lib/request.js:158
            if (param.list) {
                     ^

TypeError: Cannot read property 'list' of undefined
    at AmazonMwsRequest.set (/home/dakk/Repositories/MyRepos/ProductsBroker/node_modules/mws-api/lib/request.js:158:22)
```

**Comment by tyscorp** [comment]
I'll try to look at this sometime today or tomorrow.

**Comment by tyscorp** [comment]
I found the issue, but I believe fixing it will result in a fairly significant breaking change. I've got a few other breaking changes almost ready to released so I'll release it with those. (hopefully ASAP)

**Comment by dakk** [comment]
That's good, I'll test when it's ready; I would help you with code writing but I'm really busy in this period.

**Comment by tyscorp** [comment]
I published [v2.0.0-alpha.0](https://github.com/beardon/mws-api/releases/tag/v2.0.0-alpha.0) with these changes since the other changes were taking a lot longer than expected. You can npm install with the `@next` tag.

**Comment by xeno** [comment]
This issue is still occurring with v2.1.0, also confirmed with v2.0.0-alpha.0
